### ISSUE TITLE
Add query field for latest searches

### ISSUE THREAD

**Issue by 0xnmn** [hereisnaman/gitfame-backend#25]
Maintain a Redis Queue for 20 latest searches, including the complete user data. Push to queue only when the user is found. 

Add query latestUsers with aruguments first: Int, with return data of user type. Write resolver to get users from redis.

Use: https://github.com/NodeRedis/node_redis

**Comment by vishichoudhary** [comment]
I am working on it.

**Comment by kapillamba4** [comment]
@hereisnaman allow duplicates in redis queue?

**Comment by 0xnmn** [comment]
@kapillamba4 no not duplicates.
